services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Bebop.Identity/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: Pass@habitapi
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/identity.pfx
      Kestrel:Certificates:Default:Path: /https/identity.pfx
    ports:
      # - "5081:8080"
      - "5001:8081"
    volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./Bebop.Identity/certs:/https:ro
    networks:
      - devnet

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Bebop.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: Pass@habitapi
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/gataway.pfx
      ApiGateWaySettings:ValidApiKeys: ${GATEWAY_KEY_HABIT} 
      ApiGateWaySettings:RoomDesignerServiceBaseUrl: http://roomsdesigner-service:8080
      ApiGateWaySettings:BookOfHabitsServiceBaseUrl: http://habitsbook-service:8080
      Kestrel:Certificates:Default:Path: /https/gataway.pfx
    ports:
      - "5002:8081"
    volumes:
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./Bebop.WebAPI/certs:/https:ro
    depends_on:
      - identityserver
    networks:
      - devnet

networks:
  devnet:
    name: devnet
    driver: bridge
  
